const {
  Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType,
  LevelFormat, PageBreak, ExternalHyperlink,
} = require("docx");

const US_LETTER = { width: 12240, height: 15840 };

function h1(text) {
  return new Paragraph({ text, heading: HeadingLevel.HEADING_1, spacing: { before: 400, after: 200 } });
}
function h2(text) {
  return new Paragraph({ text, heading: HeadingLevel.HEADING_2, spacing: { before: 300, after: 150 } });
}
function h3(text) {
  return new Paragraph({ text, heading: HeadingLevel.HEADING_3, spacing: { before: 200, after: 100 } });
}
function p(text, opts = {}) {
  return new Paragraph({
    children: [new TextRun({ text, italics: !!opts.italics, bold: !!opts.bold })],
    spacing: { after: 160, line: 276 },
    alignment: opts.align || AlignmentType.JUSTIFIED,
  });
}
function bullet(text) {
  return new Paragraph({
    text,
    numbering: { reference: "main-bullets", level: 0 },
    spacing: { after: 100, line: 276 },
  });
}
function placeholder(text) {
  return new Paragraph({
    children: [new TextRun({ text: `[${text}]`, italics: true, color: "B00020" })],
    spacing: { after: 200, line: 276 },
  });
}

const doc = new Document({
  numbering: {
    config: [{
      reference: "main-bullets",
      levels: [{ level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT,
        style: { paragraph: { indent: { left: 720, hanging: 360 } } } }],
    }],
  },
  sections: [{
    properties: { page: { size: US_LETTER, margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } } },
    children: [
      // ---------------- Title ----------------
      new Paragraph({
        children: [new TextRun({
          text: "Toward a Foundation-Model Backbone for Multi-Site WiFi Indoor Localization with Hypernetwork-Based Test-Time Adaptation",
          bold: true, size: 32,
        })],
        alignment: AlignmentType.CENTER, spacing: { after: 200 },
      }),
      new Paragraph({
        children: [new TextRun({ text: "DRAFT — Results section pending final experiments (see PIVOT_PLAN.md for the complete, up-to-date experimental log)", italics: true, color: "666666" })],
        alignment: AlignmentType.CENTER, spacing: { after: 400 },
      }),
      new Paragraph({ children: [new PageBreak()] }),

      // ---------------- Abstract ----------------
      h1("Abstract"),
      p("Indoor localization from WiFi received signal strength (RSSI) fingerprints is typically trained and evaluated on a single building, which limits both the practical deployability of the resulting models and the strength of any claim to generality. We investigate whether a shared convolutional backbone, pretrained jointly across several independently collected, architecturally and geographically distinct WiFi fingerprint datasets, can function as a foundation-model-style representation for indoor localization — one that transfers to buildings it has never seen, and that can be further specialized to a target site with a small amount of additional training."),
      p("We pretrain a GlobLoc-style convolutional network — which converts each RSSI reading into a sparse “virtual-space” image anchored on known or estimated access-point positions — jointly across six sites drawn from three independently collected public datasets (HDLC, SODIndoorLoc, UJIIndoorLoc), sharing a trunk and position-regression head across all sites while giving each site its own floor-classification head. We evaluate zero-shot transfer on two sites withheld entirely from training and chosen specifically to test generalization at two different levels: one from a dataset family (UJIIndoorLoc) with two of its three buildings already represented in the pretraining pool, and one (a crowdsourced dataset collected in Tampere, Finland) from a dataset family with zero representation in pretraining at all, collected with an unrelated methodology in a different country. The shared backbone beats its naive constant-prediction baseline on both: 1.12 m versus 41.80 m on the UJIIndoorLoc site, and 1.62 m versus 30.21 m on the Tampere site."),
      p("Per-site fine-tuning improves both position and floor accuracy on every site without exception, and we benchmark the resulting per-site models directly against a recent, algorithm-matched literature comparison, closing much of the gap to published results on several sites."),
      p("Throughout the project we surface and fix a series of concrete, previously undocumented data-integrity issues — including a train/test leakage bug in two datasets' official partitions, a missing-floor-class artifact caused by coarse session-level grouping, and a rejected hypothesis about access-point sparsity — that we believe are broadly relevant to WiFi fingerprinting research beyond this specific model. Finally, we integrate a hypernetwork-based test-time adaptation (TTA) mechanism, adapted from a prior validated single-site design, intended to correct the frozen backbone's output for post-deployment drift using only unlabeled buffer statistics."),
      p("We do not report a working hypernetwork on top of this backbone. Following the oracle-diagnostic discipline described above, we tested whether a usable signal exists at all before training one, four independent ways — real single-site drift, synthetic spatially-generic drift, the same pooled across all six pretraining sites, and pooled with two further principled corrections — and all four converge on the same answer: no. Physical location dominates any drift signature we could extract, including under a strict leave-site-out test. We report this as a complete, root-caused negative finding rather than omit it or force a positive number, and treat it as evidence of a real methodological contribution in its own right."),
      p("We report all findings, including negative and partial ones, together with their root causes, rather than omitting or reframing results that did not support the initial hypothesis."),

      new Paragraph({ children: [new PageBreak()] }),

      // ---------------- 1. Introduction ----------------
      h1("1. Introduction"),
      p("Indoor positioning underlies a wide range of applications — wayfinding in large buildings, asset and personnel tracking, emergency response, and location-aware retail and facility analytics — in environments where satellite-based positioning is unavailable or unreliable. Among the many sensing modalities proposed for indoor localization, WiFi received signal strength (RSSI) fingerprinting remains the most widely deployed, since it requires no dedicated hardware beyond the WiFi infrastructure most buildings already have."),
      p("Despite over a decade of research, WiFi fingerprinting models are still almost universally trained and evaluated on a single physical site. Even the field's best-known “multi-building” benchmark, UJIIndoorLoc, is in practice consumed one building at a time by most published methods, and it is rare to find a WiFi localization model evaluated on a building it has never encountered during training at all. This is a meaningful gap: a model that must be retrained from scratch for every new deployment site is expensive to maintain at scale, and the absence of genuine cross-site evaluation makes it difficult to know whether a model's apparent accuracy reflects a transferable understanding of the localization problem, or simply memorization of one building's idiosyncrasies."),
      p("This work is motivated by the convergence of two separate lines of prior work. The first is a hypernetwork-based test-time adaptation (TTA) mechanism, validated in earlier work on a single WiFi localization pipeline, that corrects a frozen base model's final-layer weights at deployment time using only a rolling buffer of unlabeled fingerprints — no ground-truth labels are ever required post-deployment. That mechanism was designed and validated around the assumption that a competent frozen base model already exists for the deployment site in question. The second is a collaborator's GlobLoc-style convolutional pipeline, which converts each RSSI fingerprint into a small “virtual-space” image anchored on real or estimated access-point positions, and which achieves strong single-site localization accuracy."),
      p("This paper asks a direct question: can a single shared backbone, pretrained jointly across several independently collected sites, serve both as a genuinely transferable “foundation” representation for buildings it has never seen, and as the frozen base model that the hypernetwork TTA mechanism corrects at deployment time? Answering this requires solving several problems that do not arise in single-site work: reconciling incompatible dataset conventions (different access-point counts, RSSI sentinel values, and coordinate systems across sources), building genuinely leakage-free evaluation splits for sites with very different amounts of available data diversity, and designing a model architecture in which the components that should transfer across sites (position regression) and the components that inherently cannot (floor classification, since floor label spaces are not comparable across buildings) are treated differently."),
      h2("1.1 Contributions"),
      bullet("A leakage-free, multi-site pretraining protocol for WiFi RSSI fingerprint data, spanning three independently collected public datasets across three countries, with a shared, site-agnostic position-regression head and a per-site floor-classification head."),
      bullet("Demonstrated zero-shot transfer of the shared backbone to a site withheld entirely from training, with a second, independent zero-shot evaluation on a site from an unrelated dataset family."),
      bullet("A systematic per-site fine-tuning and error-analysis pipeline that surfaces and corrects several concrete data and methodology bugs, including one in the pretraining pipeline's own model-selection criterion and one in a stratified-splitting utility built to fix a different, earlier bug."),
      bullet("Integration of hypernetwork-based test-time adaptation on top of the multi-site backbone, extending a design validated in prior single-site work, together with the oracle-diagnostic discipline used to decide whether that mechanism is worth training at all in a given setting."),
      bullet("A fully transparent account of negative and partial results, including a root-caused negative oracle-diagnostic finding for TTA in a controlled single-site setting, and an explicit account of a bundled set of methodology changes that regressed model quality and had to be partially reverted."),

      new Paragraph({ children: [new PageBreak()] }),

      // ---------------- 2. Related Work ----------------
      h1("2. Related Work"),
      h2("2.1 WiFi fingerprinting and public benchmark datasets"),
      p("WiFi RSSI fingerprinting for indoor localization has been studied since the early 2000s, with methods ranging from classical k-nearest-neighbour matching against a stored radio map to deep learning approaches that treat the fingerprint vector, or a derived spatial encoding of it, as the input to a neural network. Progress in the field has been shaped substantially by a small number of public benchmark datasets. UJIIndoorLoc (Torres-Sospedra et al., 2014) was the first large-scale multi-building, multi-floor WiFi fingerprint database, covering three buildings on a Spanish university campus with 520 access points; it does not publish ground-truth access-point coordinates. SODIndoorLoc (Bi et al., 2022) was explicitly designed as a supplement to UJIIndoorLoc, covering three further buildings in different Chinese cities, and, notably, does publish ground-truth access-point positions for all three. The HDLC dataset (Nor Hisham et al., 2022) targets a different axis of the problem entirely: rather than site diversity, it collects fingerprints from the same physical corridor under three different furniture/obstruction layouts, to study robustness to indoor layout change specifically. The Tampere crowdsourced dataset (Lohan et al., 2017) contributes a fourth, independently collected site, gathered via 21 different consumer devices across a four-floor university building in Finland."),
      p("A recent comparative study (2025) benchmarked a single, algorithm-matched method (gradient-boosted trees) across the UJIIndoorLoc and SODIndoorLoc buildings, isolating dataset-specific difficulty from algorithm-specific tuning; we use these published numbers as an external point of comparison for our own per-site results."),
      h2("2.2 Foundation-model-style pretraining and transfer in sensing"),
      p("Large-scale pretraining followed by zero-shot or lightly fine-tuned transfer is now well established in vision and language, but has seen comparatively little exploration in RSSI-based indoor localization. We attribute this partly to the field's fragmentation: public datasets differ in access-point counts (from 17 to 520 in the datasets used here), RSSI “not detected” sentinel conventions, whether ground-truth access-point positions are published at all, and coordinate systems, which makes naively pooling multiple datasets into one training run nontrivial. This paper's data pipeline is built specifically to remove those obstacles."),
      h2("2.3 Test-time adaptation via hypernetworks"),
      p("The TTA mechanism extended in this work originates in prior validated work on a single WiFi localization pipeline. There, a small hypernetwork reads statistics of an unlabeled rolling buffer of fingerprints, compares them against an earlier, less-drifted reference buffer from the same deployment session, and predicts a weight delta for the frozen base model's final linear layer. That prior work established, among other things, that reference-relative buffer statistics (comparing the current buffer against an earlier one from the same site) carry a meaningfully stronger and more generalizable signal than absolute buffer statistics, and documented at least one pipeline (a channel-state-information variant) where the same mechanism, evaluated carefully, did not transfer to unseen locations despite finding a real signal in training-time cross-validation — a negative result reported openly rather than hidden. This paper adopts the same reference-relative design and the same discipline of running a cheap oracle diagnostic before committing to hypernetwork training."),

      new Paragraph({ children: [new PageBreak()] }),

      // ---------------- 3. Datasets ----------------
      h1("3. Datasets"),
      p("We use four independently collected public WiFi fingerprint datasets. Table 1 (Results section) summarizes per-site scale; this section describes each dataset's provenance and documents audit findings relevant to correct use."),
      h2("3.1 HDLC (Hybrid-fingerprint Data with Layout Change)"),
      p("Collected at the Faculty of Engineering, Multimedia University, Malaysia (Nor Hisham et al., 2022). A single physical site — the ground, first, and second floor corridors of one building wing — measured under three layout conditions created by adding partition-board obstructions to the corridor (no obstruction; obstruction on two of three floors; obstruction on all three floors). 17 WiFi access points with published ground-truth coordinates; 384 reference points on a 1-metre grid."),
      p("Audit finding: the dataset's official train/test split is row-level, not a spatial holdout — all 384 physical reference points appear in both the published training and testing files, with only the specific repeated readings at each point differing between them. Any accuracy figure computed on the official split reflects same-point interpolation, not spatial generalization. We construct our own grouped, leakage-free split (by physical reference point) throughout this work, and report the discrepancy between the two regimes explicitly where relevant."),
      h2("3.2 SODIndoorLoc"),
      p("Three buildings (CETC331, HCXY, SYL) in different Chinese cities (Bi et al., 2022), covering corridors, offices, and meeting rooms, with ground-truth access-point positions published separately for all three. CETC331 spans three floors; HCXY and SYL are each single-floor in the data variant used here."),
      p("Audit finding: CETC331's official train/test split exhibits the same row-level leakage issue found in HDLC (100% of test points also appear in training); HCXY's and SYL's official splits, by contrast, are genuine spatial holdouts (0–1% point overlap). We rebuild all three with our own grouped split for pipeline consistency."),
      h2("3.3 UJIIndoorLoc"),
      p("Three buildings on a university campus in Spain (Torres-Sospedra et al., 2014), covering up to five floors, with 520 WiFi access points and no published ground-truth access-point coordinates; positions are estimated as the RSSI-weighted centroid of locations where each access point was strongly observed. The dataset is burst-sampled by capture session (one user, one device, one contiguous walking route), which we use as the leakage-safe grouping key in place of physical point, since a point-level grouping would still leak near-duplicate same-walk fingerprints across splits."),
      p("We use buildings 1 and 2 (12 and 16 total capture sessions respectively) for pretraining, and hold building 0 (only 2 capture sessions — too thin to usefully contribute to pretraining diversity) out entirely as a zero-shot evaluation site."),
      h2("3.4 Tampere crowdsourced dataset"),
      p("A four-floor university building in Tampere, Finland (Lohan et al., 2017), collected via 21 different consumer Android devices over an eight-month crowdsourcing campaign. 992 WiFi access points, no published ground-truth positions (estimated, as with UJIIndoorLoc); grouped for leakage purposes by device model and calendar day, in the absence of an explicit session identifier."),
      p("This dataset is held out entirely from pretraining and used as a second, independent zero-shot evaluation site — deliberately chosen from a different country, collection methodology, and dataset family than any site in the pretraining pool, to test generalization beyond the UJIIndoorLoc family specifically."),

      new Paragraph({ children: [new PageBreak()] }),

      // ---------------- 4. Methodology ----------------
      h1("4. Methodology"),
      h2("4.1 Leakage-free evaluation discipline"),
      p("Every split used in this work is grouped, never row-level: for point-dense sites (HDLC, SODIndoorLoc) the group is the physical reference point; for session-burst-sampled sites (UJIIndoorLoc, Tampere) the group is the capture session (or an approximation of it, where no explicit session identifier is published). Every split is accompanied by an explicit assertion that no group appears in more than one of train, validation, and test."),
      p("For sites with very few groups — UJIIndoorLoc's buildings have only 12–16 total capture sessions — a naive random grouped split can leave an entire floor class entirely absent from one partition. We found, in the course of this work, that this occurred in two different directions: first, a floor absent from the test partition (so the model's occasional predictions of that floor were automatically wrong, with nothing to be automatically right against, inflating the apparent error); and second, in an early attempt to fix the first problem, a floor absent from the training partition instead (so the model could never have learned to predict it correctly in the first place, which we judge to be the worse failure mode of the two). Our final stratified splitting procedure guarantees every floor class is represented in the training partition, and only attempts to also guarantee validation/test representation when doing so provably cannot remove a floor's last remaining training group."),
      p("A naive constant-prediction baseline — predicting the training set's mean position and majority-class floor for every evaluation row — is computed and reported for every model, as a sanity floor any real model is expected to clear."),
      h2("4.2 Virtual-space RSSI imaging and CNN backbone"),
      p("Following the GlobLoc approach, each RSSI reading is converted into a small single-channel image rather than consumed as a raw feature vector. The k strongest-detected access points that also have a known (or estimated) physical position are placed as pixels at their real-world coordinates, at a fixed spatial resolution; pixel intensity is the access point's normalized signal strength. The position-regression target is expressed in local pixel coordinates relative to that image's own origin — not the raw global coordinate system of the site — which is the key design property that lets a single shared regression head operate across sites with entirely different absolute coordinate systems and scales."),
      p("The backbone is a five-block convolutional trunk (each block: two 3×3 convolutions with group normalization and a leaky-ReLU activation, followed by max-pooling), followed by spatial pyramid pooling to accommodate the variable image sizes that result from different fingerprints having different numbers and spatial spreads of visible access points, feeding a shared 128-dimensional bottleneck."),
      h2("4.3 Multi-site joint pretraining"),
      p("The convolutional trunk and the position-regression head are shared across all pretraining sites, since the regression target is already locally normalized and therefore not tied to any one site's coordinate system. Floor prediction is not shared: each site is given its own small linear head off the same shared bottleneck, since floor label spaces are not semantically comparable across buildings (building A's “floor 2” bears no relationship to building B's “floor 2”)."),
      p("Naive concatenation of all sites' training rows under-represents small sites relative to large ones — in our pool, site sizes range from roughly 1,800 to 12,000 rows. We use a site-balanced sampler that oversamples every site, with replacement, up to the size of the largest site, which corrects this without ever reducing a large site's exposure relative to plain concatenation."),
      p("Floor confusion-matrix analysis (Section 5, error analysis) showed that floor misclassifications are consistently adjacent-biased — floor 0 is confused with floor 1 far more often than with floor 2 — a pattern plain multi-class cross-entropy cannot exploit, since it treats every incorrect class as equally wrong. We therefore train floor prediction as a bounded ordinal regression (a single scalar output per site, trained with a robust regression loss against the floor index, rounded and clamped to the valid range at inference) rather than as classification."),
      h2("4.4 Per-site fine-tuning"),
      p("Starting from the jointly pretrained checkpoint, the shared position-regression head is frozen — to preserve the cross-site transfer property validated by zero-shot evaluation — while the convolutional trunk and that site's own floor head are adapted at a reduced learning rate using only that site's own training data. This mirrors the standard “pretrain, then fine-tune” transfer-learning pattern, with the frozen component chosen specifically to be the one whose generality has independent evidence behind it."),
      p("Two methodology issues were found and corrected during this stage. First, checkpoint selection during both joint training and fine-tuning initially used position error alone, which was found to silently prefer checkpoints with worse floor accuracy at equivalent or better position error; selection now uses a combined position-and-floor metric. Second, a fixed fine-tuning epoch budget under-trained some sites relative to others (session-grouped sites with few groups converge on a very different timescale than point-dense sites with hundreds of groups); we replaced the fixed budget with patience-based early stopping on the combined validation metric, with a generous maximum-epoch safety cap."),
      h2("4.5 Hypernetwork test-time adaptation"),
      p("On top of the frozen, fine-tuned per-site backbone, we integrate a hypernetwork-based test-time adaptation mechanism, adapted from the prior validated single-site design referenced in Section 2.3. The hypernetwork observes reference-relative buffer statistics — comparing a current, unlabeled rolling buffer of recent fingerprints against an earlier, less-drifted reference buffer collected at deployment start from the same site — and predicts a weight delta for the frozen backbone's position-output layer, added on top of (not replacing) the frozen weights. The hypernetwork's output layers are zero-initialized, so an untrained or low-confidence hypernetwork is a no-op correction rather than an active source of error."),
      p("Consistent with the discipline established in prior work, we do not train the hypernetwork on any site until a cheap oracle diagnostic — a leave-groups-out regression from buffer statistics to drift-induced localization error, compared explicitly against a naive “physical point or session identity alone” predictor — shows a real, non-confounded, transferable signal. If identity alone predicts drift-induced error better than the actual buffer statistics do, that is treated as a confound warning sign, not a green light, regardless of how promising the raw signal looks in isolation."),
      p("We ran this diagnostic five times, each a genuinely different test rather than a repetition: (i) on HDLC alone using its own real, physically-caused drift (partition-board obstructions at fixed corridor locations); (ii) on HDLC alone using synthetic, spatially-generic drift (a random-walk RSSI attenuation plus ramping access-point dropout, with severity drawn independently per buffer instance, decoupled from location); (iii) the same synthetic mechanism pooled across all six pretraining sites, with a leave-entire-site-out test added as the strictest possible generalization check; (iv) the pooled setting again with two principled corrections — removing a feature that directly encoded site identity, and normalizing the prediction target to each site's own baseline, which is the conceptually correct framing for drift-relative-to-normal in the first place; and (v) replacing the hand-crafted buffer statistics entirely with a feature source of a genuinely different kind — displacement in the frozen backbone's own learned 128-dimensional bottleneck embedding between a reference and a current buffer, on the reasoning that a representation already optimized for localization might carry drift information more directly than generic RSSI summary statistics. Full detail in Section 7.5 and PIVOT_PLAN.md."),

      new Paragraph({ children: [new PageBreak()] }),

      // ---------------- 5. Experimental Setup ----------------
      h1("5. Experimental Setup"),
      p("All splits use a 70/15/15 train/validation/test ratio by group (physical point or capture session, as appropriate to the site), with the stratified-by-floor procedure described in Section 4.1 applied uniformly. Virtual-space images use the k=5 strongest positioned access points per reading, a 2-metre margin around the bounding box of those access points' positions, and a 10-metre maximum extent from the strongest access point, at 0.5-metre pixel resolution. Joint pretraining uses the Adam optimizer; fine-tuning uses a reduced learning rate on top of the pretrained weights, consistent with standard transfer-learning practice."),
      p("Evaluation metrics are: median position error in metres; floor classification accuracy (exact match after rounding the ordinal regression output); floor mean absolute error (in floor units, for comparison against literature that reports this metric); and a combined position-and-floor error that converts a floor-count discrepancy into an equivalent metre distance using each dataset's documented inter-floor height, for a single summary number where floor labels are available."),
      p("For every model, we report the naive constant-prediction baseline computed on the identical split, and, where an external comparison exists, the corresponding published literature figure computed with a matched algorithm on the same building."),

      new Paragraph({ children: [new PageBreak()] }),

      // ---------------- 6. Results ----------------
      h1("6. Results"),
      placeholder("Results section intentionally left for the authors to complete from the finalized experimental log (PIVOT_PLAN.md) once the current retraining run and the hypernetwork TTA component are finished. Suggested subsections: 6.1 Per-site pretraining vs. naive baseline; 6.2 Zero-shot transfer (uji_b0, and Tampere if completed in time); 6.3 Per-site fine-tuning vs. literature; 6.4 Error analysis (spatial heatmaps, floor confusion, AP-sparsity check); 6.5 Hypernetwork TTA oracle diagnostic and deployment simulation."),

      new Paragraph({ children: [new PageBreak()] }),

      // ---------------- 7. Discussion and Limitations ----------------
      h1("7. Discussion and Limitations"),
      p("We report the following limitations plainly, as part of the contribution rather than as an afterthought."),
      h2("7.1 Zero-shot evidence is still limited to two sites"),
      p("Genuine zero-shot transfer succeeds on both sites we tested it against: UJIIndoorLoc building 0 (1.12 m vs. 41.80 m naive), which tests generalization within a dataset family two-thirds represented in pretraining, and the Tampere dataset (1.62 m vs. 30.21 m naive), which tests generalization to a dataset family with zero representation in pretraining at all — a different country, a different collection methodology (crowdsourced across 21 devices), and no shared provenance with any pretraining site. That the backbone transfers to both, and that the harder of the two tests (Tampere) still clears its naive baseline by roughly 19×, is considerably stronger evidence than a single success would be that the shared representation has learned something genuinely transferable rather than memorizing per-site quirks. It is still evidence from two sites, not a systematic sweep; a stronger generality claim would benefit from zero-shot evaluation against additional dataset families beyond the four used in this work."),
      h2("7.2 Position-error comparability across sites"),
      p("The virtual-space representation used throughout this work gives the position-regression task a locality prior that literature methods regressing position directly from a raw, un-anchored RSSI vector do not receive: each image is built from a small window anchored on nearby known or estimated access-point positions, and the regression target is expressed relative to that local window rather than in absolute site coordinates. This plausibly explains why our position-error numbers compare very favourably to literature on sparse, large-access-point-count sites (UJIIndoorLoc, Tampere) specifically — the two site families where this locality prior matters most. We caution against reading a favourable position-error comparison on those sites as direct evidence that the learned trunk features are as broadly general as the apparent numbers suggest; the comparison is more directly meaningful on dense, fully-positioned sites (HDLC, SODIndoorLoc) where the locality prior's effect is much smaller."),
      h2("7.3 Floor classification on sparse-access-point sites"),
      p("Floor classification accuracy on the UJIIndoorLoc sites trails a matched literature benchmark by a substantial margin even after targeted fine-tuning, though the gap narrowed considerably over the course of iterative fixes described in this work. Error analysis attributed part of the original gap to a genuine data-methodology artifact — an entire floor class silently absent from one site's test partition, inflating the apparent error — which is now corrected; the remaining gap is more plausibly attributable to those sites' very sparse and only partially estimated access-point position coverage (roughly 30% of access points have any position estimate at all, versus 100% ground-truth coverage on the dense sites), which limits how much of the available RSSI signal the virtual-space encoding can represent in the first place."),
      h2("7.4 A cautionary note on bundling untested changes"),
      p("In an effort to save wall-clock time under deadline pressure, we once combined three independently well-motivated methodology changes — a data-split fix, a loss-function change, and a virtual-space hyperparameter change — into a single retraining pass. The result was an unambiguous regression across nearly every site, including the headline zero-shot metric, which we traced most plausibly to the hyperparameter change (a uniformly widened search radius, intended to help only the minority of peripheral/edge-of-coverage points, applied instead to every point) rather than the other two changes, but could not cleanly isolate from that single bundled run. We record this as a methodological caution: bundling changes to save time trades away the ability to attribute cause when something goes wrong, and something did."),
      h2("7.5 A negative test-time-adaptation finding in a controlled single-site setting"),
      p("Prior to the multi-site work described in this paper, we ran the oracle-diagnostic protocol described in Section 4.5 on the HDLC dataset alone, using its own real (not synthetic) drift conditions — the three physical layout/obstruction variants described in Section 3.1 — as the deployment-drift scenario. The diagnostic returned a clear negative result: leave-points-out regression from reference-relative buffer statistics to drift-induced localization error achieved negative predictive R² (i.e., performed worse than predicting the mean), for both a linear and a nonlinear regressor, and a naive “physical point identity alone” predictor substantially outperformed the buffer-statistics-based predictors under a matched, non-grouped cross-validation — the exact confound signature the diagnostic exists to catch. We attribute this to the specific character of HDLC's drift: physical obstructions placed at fixed corridor locations produce a drift signature that is entangled with location by the structure of the experiment itself, unlike the spatially generic (e.g., temporal or session-to-session) drift mechanisms under which the prior single-site hypernetwork design found at least a weak, real signal. We did not proceed to hypernetwork training on this dataset, consistent with the discipline of not forcing a mechanism past a negative diagnostic."),
      p("Repeating the diagnostic with synthetic, spatially generic drift instead of HDLC's real obstruction drift confirms this root cause directly: a real, non-negative signal appears where there was none before (leave-points-out R² moves from -0.070 to 0.096 for a random forest, and from -0.098 to 0.057 for a linear ridge regression), which is direct evidence that the original negative result was about HDLC's specific drift structure, not an inherent property of buffer statistics or this backbone. It is not, however, sufficient to proceed: point identity alone still explains more of the variance (R²=0.333) than the buffer statistics do, the same confound signature the diagnostic exists to catch, just less severe. Pooling the same diagnostic across all six pretraining sites — hypothesising that HDLC's small pool of 116 held-out points was itself inflating the apparent importance of location — made the confound worse, not better (identity R²=0.685), and a leave-entire-site-out test (predicting an unseen site's drift-induced error using only patterns learned from other sites) was negative (R²=-0.052). Two further, principled corrections — removing a feature that directly encoded site identity, and normalizing the prediction target to each site's own baseline rather than an absolute scale — did not recover a cross-site signal either (leave-site-out R²=-0.268 after normalization)."),
      p("As a fifth and final trial, we replaced the feature source itself rather than continuing to vary corrections applied to the same hand-crafted RSSI statistics: the buffer signature became displacement, between reference and current buffer, in the frozen backbone's own 128-dimensional bottleneck embedding — a representation already optimized for localization, and dimension-independent by construction, so it cannot leak site identity through raw access-point count the way the earlier feature set could. The result was negative again, and leave-site-out generalization was in fact worse than every RSSI-statistics version tried (R²=-0.684 normalized, -1.184 raw, versus -0.047 to -0.268 for the RSSI-based trials). We root-caused this rather than treating it as simply one more negative number. The most direct hypothesis — that per-site fine-tuning (Section 4.4) had caused the six sites' trunks to diverge enough that they no longer shared one embedding space at all — was tested directly in weight space and rejected: every fine-tuned trunk stayed within 0.8%–4.3% relative L2 distance of the pre-fine-tune joint checkpoint, with pairwise cosine similarity above 0.999 throughout. A second analysis found a real but modest contributing factor: the median embedding displacement varies by roughly 31% across sites despite the near-identical trunks, a scale inconsistency the raw RSSI statistics do not have, since those are normalized into a common physical unit range before any nonlinear transform sees them. The clearest evidence, however, came from inspecting the leave-site-out predictions directly: on a held-out site, predicted values collapsed into a narrow, nearly constant band regardless of the true target's much wider range — the regressor was not tracking drift severity for an unseen site at all, only reproducing something close to the pooled training mean. We interpret this as showing that a bottleneck trained purely to make position and floor decodable does not reliably preserve drift-severity information in a form that is consistent across sites with very different native access-point counts and layouts (17 dense access points at HDLC versus 520 sparse access points at UJIIndoorLoc); whatever weak correlation exists is site-idiosyncratic rather than a transferable physical signal."),
      p("We treat this as a complete, five-times-replicated negative finding, the last of which is mechanistically explained rather than left as an additional unexplained data point: reference-relative buffer statistics — whether hand-crafted RSSI summaries or the backbone's own learned embeddings — do not carry a usable signal about drift-induced localization error that generalizes across physical locations or across sites in this setting, and we do not proceed to hypernetwork training on top of this backbone as a result. We consider a rigorously falsified hypothesis, investigated this thoroughly, a more valuable and more honest contribution than an unvalidated positive result would have been."),

      new Paragraph({ children: [new PageBreak()] }),

      // ---------------- 8. Conclusion ----------------
      h1("8. Conclusion"),
      p("This work set out to test whether a single WiFi RSSI localization backbone, pretrained jointly across multiple independently collected sites, can serve as both a genuinely transferable foundation representation and a suitable frozen base for hypernetwork-based test-time adaptation. We built a leakage-free, multi-site pretraining and fine-tuning pipeline spanning three public dataset families and demonstrated zero-shot position transfer to a site withheld entirely from training. Along the way we found, root-caused, and corrected several concrete data and methodology issues — split leakage in two datasets' official partitions, a missing-floor-class evaluation artifact, a flawed model-selection criterion, and the consequences of bundling untested changes under time pressure — which we report in full because we believe several of them are relevant to WiFi fingerprinting research beyond this specific model. We integrated hypernetwork-based test-time adaptation on top of the resulting backbone, carrying forward a design and an evaluation discipline validated in prior single-site work, including a negative oracle-diagnostic result from a controlled single-site setting that motivates caution rather than an assumption of success."),
      p("We consider the central, defensible claim of this work to be narrower than “we built a foundation model for indoor localization”: this is evidence that the foundation-model-style pretraining strategy — shared backbone, multi-site diversity, zero-shot and fine-tuned reuse — works at a demonstrated small scale for this task, with one validated zero-shot success, not a claim that the resulting model is general enough to deserve the label without qualification. We regard closing that gap, honestly, as the natural next step."),

      new Paragraph({ children: [new PageBreak()] }),

      // ---------------- 9. Future Work ----------------
      h1("9. Future Work"),
      bullet("Broaden zero-shot validation to a larger and more diverse set of held-out sites, ideally including at least one additional dataset family beyond those used here."),
      bullet("Report literature-comparable, un-anchored (“blind”) position-regression baselines on the same sites, to separate the virtual-space representation's inherent locality prior from the learned backbone's actual transferability."),
      bullet("Investigate spatially adaptive virtual-space window sizing (wider only for peripheral/edge-of-coverage points, informed by the error-clustering pattern found in this work) as a more targeted alternative to the uniformly widened window that regressed overall model quality when tried."),
      bullet("Complete the multi-site hypernetwork TTA evaluation with a full, multi-seed deployment simulation, calibrating any deployment-affecting hyperparameter (correction clipping, buffer size and cadence, gating thresholds) on held-out training data only, never on the final test set."),
      bullet("Evaluate the hypernetwork mechanism against the genuinely longitudinal (20-month) long-term WiFi drift dataset identified during this work (Mendoza-Silva et al., 2018) as a real, non-synthetic drift benchmark, rather than relying solely on HDLC's location-entangled real drift or a synthetic drift injector."),

      new Paragraph({ children: [new PageBreak()] }),

      // ---------------- References ----------------
      h1("References"),
      p("Nor Hisham, A. N., Ng, Y. H., Tan, C. K., & Chieng, D. (2022). Hybrid Wi-Fi and BLE Fingerprinting Dataset for Multi-Floor Indoor Environments with Different Layouts. Data, 7(11), 156. https://doi.org/10.3390/data7110156", { align: AlignmentType.LEFT }),
      p("Bi, J., Wang, Y., Yu, B., et al. (2022). Supplementary open dataset for WiFi indoor localization based on received signal strength. Satellite Navigation, 3, 25. https://doi.org/10.1186/s43020-022-00086-y", { align: AlignmentType.LEFT }),
      p("Torres-Sospedra, J., Montoliu, R., Martinez-Uso, A., Avariento, J. P., Arnau, T. J., Benedito-Bordonau, M., & Huerta, J. (2014). UJIIndoorLoc: A New Multi-Building and Multi-Floor Database for WLAN Fingerprint-Based Indoor Localization Problems. Proceedings of the 2014 International Conference on Indoor Positioning and Indoor Navigation (IPIN), 261–270.", { align: AlignmentType.LEFT }),
      p("Lohan, E. S., Torres-Sospedra, J., Richter, P., Leppäkoski, H., Huerta, J., & Cramariuc, A. (2017). Wi-Fi Crowdsourced Fingerprinting Dataset for Indoor Positioning. Data, 2(4), 32. https://doi.org/10.3390/data2040032", { align: AlignmentType.LEFT }),
      p("Mendoza-Silva, G. M., Richter, P., Torres-Sospedra, J., Lohan, E. S., & Huerta, J. (2018). Long-Term WiFi Fingerprinting Dataset for Research on Robust Indoor Positioning. Data, 3(1), 3. https://doi.org/10.3390/data3010003", { align: AlignmentType.LEFT }),
      placeholder("Comparative benchmark paper (2025, Scientific Reports — XGBoost comparison across UJIIndoorLoc/SODIndoorLoc). Full citation to be confirmed."),
      placeholder("Self-citation: prior hypernetwork test-time adaptation project (title/venue to be confirmed by the authors)."),
    ],
  }],
});

Packer.toBuffer(doc).then((buf) => {
  require("fs").writeFileSync(__dirname + "/paper_draft_v2.docx", buf);
  console.log("wrote paper_draft_v2.docx");
});
